Replace comparisons with wrappers
willow-ahrens/Finch.jl pull request #294
Opened 2023-09-30 19:26 UTC by radha-patel

Replace `<`, `<=`, `>`, `>=`, and `=` involving index comparisons with appropriate masks.

2023-09-30 21:31 UTC, willow-ahrens commented
is it possible to handle != as well, by putting a ! in front of the diagonal mask?

2023-10-01 00:43 UTC, willow-ahrens commented
it looks like some of the tests for conversions with triangle levels have failed. could you take a look at the logs to see if you can reproduce?

2023-10-01 01:05 UTC, radha-patel commented
> it looks like some of the tests for conversions with triangle levels have failed. could you take a look at the logs to see if you can reproduce?

Yep! I'm looking now

2023-10-01 01:18 UTC, willow-ahrens requested changes
In addition to the more specific comments, none of these cases actually swap the order of i and j depending on which is bound first.

2023-10-01 01:18 UTC, willow-ahrens commented on src/transforms/wrapperize.jl
> +        end),
Could we refactor each of these rules into two cases:
```
        (@rule call(<, ~i, ~j::isindex) => begin
            if depth(i) < depth(j)
                access(UpTriMask(), reader(), j, call(-, i, 1))
            end
        ),
        @rule call(<, ~i::isindex, ~j) => begin
            if depth(i) > depth(j)
                access(LoTriMask(), reader(), i, call(+, j, 1))
            end
        ),
 ```
 This code is different in a few ways:
 1. Only the inner (fast) index needs to be a vanilla index (as opposed to `i + 1`, etc.).
 2. This code flips the index order in order to always emit a column major access.

2023-10-01 01:18 UTC, willow-ahrens commented on src/transforms/wrapperize.jl
> +        end),
These two rules are not always emitting column major code

2023-10-02 00:49 UTC, radha-patel commented
@willow-ahrens I've addressed your comments!

2023-10-05 15:54 UTC, merged