Swizzle back in `copyto!`
willow-ahrens/Finch.jl pull request #390
Opened 2024-01-29 14:44 UTC by mtsokol

Hi @willow-ahrens,

I took a look at #387 and I think that `return ret.body` causes omitting "swizzling" back to the desired dimensionality in some `copyto!` functions. I just started learning how it works so I might have misunderstood it.

2024-01-29 15:55 UTC, willow-ahrens commented
Awesome, thanks so much for the fix! Could you add a quick test case and then I'll merge?

2024-01-29 18:39 UTC, willow-ahrens requested changes
Looks great! Just needs at least one test

2024-01-29 19:28 UTC, mtsokol commented
@willow-ahrens I added a test that checks `permutedims` for 3d tensor with different shapes. I think that the current fix isn't sufficient as some of the test cases fail with incorrect shapes compared to `Base.permutedims`.

2024-01-29 20:35 UTC, willow-ahrens commented
I think the main issue here is that Finch seems to drop the swizzle wrapper on the output. This is a little bit of a tricky fix, I'll need to look at it tonight and get back to you.

2024-01-29 20:45 UTC, mtsokol commented
Thank you! For me it's a bit difficult to follow code considering that ’tocopy!’ both returns a value and mutates passed argument for the same purpose. And it seems that IT matters which one is used in different places.

2024-01-30 14:09 UTC, willow-ahrens commented
The main issue is here: https://github.com/willow-ahrens/Finch.jl/blob/0a536c7f43ef76ffd55ca0a927e654466e1efda8/src/transforms/wrapperize.jl#L181-L188 

In these lines of code, Finch is stripping the swizzle off of the tensor, and doesn't have a way to re-wrap the tensor before return.

2024-02-14 14:17 UTC, closed without merging